In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

In [41]:
avg = pd.read_csv('./etc_data/avg_visitor.csv', encoding='cp949')
carbon = pd.read_csv('./etc_data/tourism_emission.csv')
price = pd.read_csv('./etc_data/enter_final.csv', encoding='cp949')

In [42]:
avg

           TRRSRT_NM  AVERAGE_VISITOR
0              2월22일         2.000000
1              감귤박물관       279.455556
2            건강과성박물관        11.645455
3              고스트타운         5.857143
4             고흐의 정원         5.212766
..               ...              ...
120  해비치호텔앤드리조트(하노루)         1.000000
121             허브동산        17.120968
122         헬로키티아일랜드        41.929825
123              화조원        47.792899
124            환상의짜장         3.360000

[125 rows x 2 columns]

In [44]:
carbon['TRRSRT_NM'].unique()

array(['건강과성박물관', '고흐의 정원', '그대나의뮤즈', '그림포레스트', '노형수퍼마_', '빛의벙커',
       '세계자동차박물관', '숨도박물관', '아이스뮤지엄(수목원테마파크)', '아프리카박물관', '유리박물관',
       '점보빌리지', '제주해양동물박물관', '초콜릿랜드', '캐릭파크', '테디베어뮤지엄 제주', '피규어뮤지엄',
       '헬로키티아일랜드', '2월22일', '고스트타운', '그림카페', '꽃썸', '더힐링타임', '디저트팩토리',
       '마돈가', '마라도가는여객선', '마라도정기여객선', '망고홀릭종달점', '바다의향기', '본초족욕 수목원테마파크',
       '봄그리고가을리조트', '사뿐', '산방산탄산온천', '삼성혈', '성산포유람선', '쇠소깍산물관광농원',
       '영주말가든', '오늘은 녹차 족욕', '오설록 티뮤지엄', '제주수목원 플레이박스', '제주오메오메', '진돼지',
       '코코몽에코파크', '테라피샹그릴라', '토스카나호텔', '토종흑염소농장', '해비치호텔앤드리조트(섬모라)',
       '해비치호텔앤드리조트(하노루)', '환상의짜장', '김녕요트투어', '대유 ATV 수렵 사격랜드',
       '마라도정기여객선(운진항)', '비양도 도항선', '산방산유람선', '서귀포다이브', '서귀포유람선', '서귀포잠수함',
       '서피플', '세리월드', '송악왕발통', '송악카트체험장', '우도잠수함', '윈드1947 서바이벌',
       '제주레일바이크', '제주바다체험장', '제주실탄사격장', '제주카약', '조랑말타운 승마카트', '중문레져UTV',
       '차귀도 달래배낚시', '차귀도유람선', '코바다이빙스쿨', '포니밸리 낙타테마파크', '하늘여행 행글라이더',
       '제주민속촌', '만장굴', '비자림', '산방산 암벽식물지대', '상효원', '생각하는정원', '성산일출봉',
       '여미지식물원', '용머리해안', '정방폭포', '주상절리대', '천제연폭포', '천지연폭포', '새별헤이요',
       '공룡랜드', '돈키쥬쥬', '뽀로로앤타요 테마파크', '시크릿테마파크', '액트몬(신화월드점)', '감귤박물관',
       '그리스신화박물관', '노리매테마파크', '다이나믹메이즈에피소드3', '더마파크', '메이즈랜드', '방림원',
       '브릭캠퍼스', '생각하는정원(분재예술원)', '센트럴파크', '소인국테마파크', '스누피가든', '신화테마파크제주',
       '아이스뮤지엄', '일출랜드', '제주돌마을공원', '제주돌문화공원', '제주무민랜드', '제주유리의성',
       '제주조각공원', '카멜리아힐', '테디베어뮤지엄제주', '하모씨워킹', '한림공원', '허브동산', '화조원'],
      dtype=object)

In [5]:
price

,CL_NM,TRRSRT_NM,ADDR,TOT_ENTRN_NMPR_CO,SETLE_PRICE,PRICE_PER_PERSON
0,공연전시,건강과성박물관,서귀포시 안덕면 일주서로 1611,895,9429670,10535.9
1,공연전시,고흐의 정원,서귀포시 성산읍 삼달신풍로 126-5,245,1781500,7271.4
2,공연전시,그대나의뮤즈,서귀포시 안덕면 신화역사로304번길 89,325,4801000,14772.3
3,공연전시,그림포레스트,서귀포시 중문관광로110번길 32,199,2005000,10075.4
4,공연전시,노형수퍼마켙,제주시 노형로 89,1407,19867560,14120.5
...,...,...,...,...,...,...
153,테마관광,하모씨워킹,서귀포시 대정읍 최남단해안로 120,17,613500,36088.2
154,테마관광,한림공원,제주시 한림읍 한림로 300,11783,141691660,12025.1
155,테마관광,허브동산,서귀포시 표선면 돈오름로 170,2123,20625010,9715.0
156,테마관광,헬로키티아일랜드,서귀포시 안덕면 한창로 340,4278,55806450,13045.0
157,테마관광,화조원,제주시 애월읍 애원로 804,8077,107955380,13365.8

In [6]:
carbon.drop('Unnamed: 0', axis=1, inplace = True)

In [7]:
carbon['Avg_Gas'] = carbon['Gas'] / carbon['AVERAGE_VISITOR']

In [8]:
carbon

    CL_NM TRRSRT_NM           ADDR  AVERAGE_VISITOR        Gas    Avg_Gas
0    공연전시   건강과성박물관      일주서로 1611             10.5  10.268741   0.977975
1    공연전시    고흐의 정원    삼달신풍로 126-5              5.2   0.264908   0.050944
2    공연전시    그대나의뮤즈  신화역사로304번길 89              8.3  93.480535  11.262715
3    공연전시    그림포레스트  중문관광로110번길 32              9.0  18.391061   2.043451
4    공연전시    노형수퍼마_         노형로 89             16.8   7.498472   0.446338
..    ...       ...            ...              ...        ...        ...
144  테마관광     하모씨워킹     최남단해안로 120              3.4        NaN        NaN
145  테마관광      한림공원        한림로 300             75.5  20.802554   0.275531
146  테마관광      허브동산       돈오름로 170             17.1   8.259299   0.483000
147  테마관광  헬로키티아일랜드        한창로 340             49.7  15.460906   0.311085
148  테마관광       화조원        애원로 804             47.8        NaN        NaN

[149 rows x 6 columns]

In [9]:
price_per = price['PRICE_PER_PERSON']

In [10]:
price_per

0      10535.9
1       7271.4
2      14772.3
3      10075.4
4      14120.5
        ...
153    36088.2
154    12025.1
155     9715.0
156    13045.0
157    13365.8
Name: PRICE_PER_PERSON, Length: 158, dtype: float64

In [11]:
carbon['price_per_person'] = price_per

In [12]:
carbon

,CL_NM,TRRSRT_NM,ADDR,AVERAGE_VISITOR,Gas,Avg_Gas,price_per_person
0,공연전시,건강과성박물관,일주서로 1611,10.5,10.268741,0.977975,10535.9
1,공연전시,고흐의 정원,삼달신풍로 126-5,5.2,0.264908,0.050944,7271.4
2,공연전시,그대나의뮤즈,신화역사로304번길 89,8.3,93.480535,11.262715,14772.3
3,공연전시,그림포레스트,중문관광로110번길 32,9.0,18.391061,2.043451,10075.4
4,공연전시,노형수퍼마_,노형로 89,16.8,7.498472,0.446338,14120.5
...,...,...,...,...,...,...,...
144,테마관광,하모씨워킹,최남단해안로 120,3.4,NaN,NaN,9129.4
145,테마관광,한림공원,한림로 300,75.5,20.802554,0.275531,9255.3
146,테마관광,허브동산,돈오름로 170,17.1,8.259299,0.483000,5609.5
147,테마관광,헬로키티아일랜드,한창로 340,49.7,15.460906,0.311085,7044.6
148,테마관광,화조원,애원로 804,47.8,NaN,NaN,2500.0

In [24]:
carbon['NEW_CL'] = np.nan

In [15]:
carbon.to_csv('enter_carbon.csv', header=True, index=False, encoding="cp949")

In [17]:
carbon['CL_NM'].unique()

array(['공연전시', '기타', '레저', '문화관광', '자연', '체험', '키즈', '테마관광'], dtype=object)

In [26]:
for i in range(len(carbon)):
    if '박물관' in carbon['TRRSRT_NM'][i]:
        carbon['NEW_CL'][i] = '박물관'
    elif '뮤지엄' in carbon['TRRSRT_NM'][i]:
        carbon['NEW_CL'][i] = '박물관'

/var/folders/_t/yrhf8bh167g1b6qb6gqjrf_c0000gn/T/ipykernel_2680/3706346449.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  carbon['NEW_CL'][i] = '박물관'

In [27]:
carbon

,CL_NM,TRRSRT_NM,ADDR,AVERAGE_VISITOR,Gas,Avg_Gas,price_per_person,NEW_CL
0,공연전시,건강과성박물관,일주서로 1611,10.5,10.268741,0.977975,10535.9,박물관
1,공연전시,고흐의 정원,삼달신풍로 126-5,5.2,0.264908,0.050944,7271.4,NaN
2,공연전시,그대나의뮤즈,신화역사로304번길 89,8.3,93.480535,11.262715,14772.3,NaN
3,공연전시,그림포레스트,중문관광로110번길 32,9.0,18.391061,2.043451,10075.4,NaN
4,공연전시,노형수퍼마_,노형로 89,16.8,7.498472,0.446338,14120.5,NaN
...,...,...,...,...,...,...,...,...
144,테마관광,하모씨워킹,최남단해안로 120,3.4,NaN,NaN,9129.4,NaN
145,테마관광,한림공원,한림로 300,75.5,20.802554,0.275531,9255.3,NaN
146,테마관광,허브동산,돈오름로 170,17.1,8.259299,0.483000,5609.5,NaN
147,테마관광,헬로키티아일랜드,한창로 340,49.7,15.460906,0.311085,7044.6,NaN
148,테마관광,화조원,애원로 804,47.8,NaN,NaN,2500.0,NaN

In [42]:
carbon[carbon['Avg_Gas'].isnull() == True]

,CL_NM,TRRSRT_NM,ADDR,AVERAGE_VISITOR,Gas,Avg_Gas,price_per_person,NEW_CL
5,공연전시,빛의벙커,고성리 2039-22,424.6,NaN,NaN,17564.5,NaN
20,기타,그대나의뮤즈,제주신화월드 서머셋클럽하우스,23.4,NaN,NaN,14611.9,NaN
25,기타,마돈가,17 제주진미마돈가,3.0,NaN,NaN,28613.3,NaN
26,기타,마라도가는여객선,424 마라도여객선매표소,17.8,NaN,NaN,16697.0,NaN
27,기타,마라도정기여객선,최남단해안로 120,16.4,NaN,NaN,17114.4,NaN
28,기타,망고홀릭종달점,종달논길 18,3.0,NaN,NaN,0.0,NaN
31,기타,봄그리고가을리조트,2660 시흥근생및주택,15.1,NaN,NaN,9676.9,NaN
32,기타,빛의벙커,고성리 2039-22,754.1,NaN,NaN,17519.9,NaN
34,기타,사뿐,36 원화하이츠빌라,1.0,NaN,NaN,8640.0,NaN
37,기타,성산포유람선,성산읍 성산리,6.7,NaN,NaN,12680.9,NaN
38,기타,세계자동차박물관,세계자동차 제주박물관,12.2,NaN,NaN,11524.0,박물관
39,기타,쇠소깍산물관광농원,하례로 90,2.0,NaN,NaN,4000.0,NaN
40,기타,영주말가든,연북로 196,3.1,NaN,NaN,27471.2,NaN
41,기타,오늘은 녹차 족욕,중산간동로 4772,2.0,NaN,NaN,8000.0,NaN
42,기타,오설록 티뮤지엄,신화역사로 15,15.2,NaN,NaN,21661.1,박물관
46,기타,코코몽에코파크,536 제주코코몽에코파크,10.8,NaN,NaN,13314.4,NaN
47,기타,테라피샹그릴라,44 2층,2.3,NaN,NaN,72619.0,NaN
52,기타,환상의짜장,마라로 45,3.5,NaN,NaN,1556.4,NaN
56,레저,마라도정기여객선(운진항),최남단해안로 120,8.9,NaN,NaN,16393.8,NaN
60,레저,서귀포다이브,하례망장포로 65-13,2.0,NaN,NaN,59175.0,NaN
64,레저,성산포유람선,성산읍 성산리,15.5,NaN,NaN,11986.4,NaN
66,레저,송악왕발통,상모리 138-3,4.5,NaN,NaN,19500.0,NaN
68,레저,우도잠수함,성산등용로 112-7,27.2,NaN,NaN,36082.1,NaN
71,레저,제주바다체험장,동복리 608-3,4.0,NaN,NaN,7689.0,NaN
75,레저,중문레져UTV,대포동 산39-5,2.7,NaN,NaN,82939.0,NaN
86,자연,산방산 암벽식물지대,산 16,401.9,NaN,NaN,15316.5,NaN
87,자연,상효원,산록남로 2847-37,7.7,NaN,NaN,9000.0,NaN
88,자연,생각하는정원,675 생각하는정원,7.2,NaN,NaN,92963.9,NaN
90,자연,여미지식물원,중문관광로 93,60.4,NaN,NaN,13000.0,NaN
91,자연,용머리해안,안덕면 사계리,2102.1,NaN,NaN,58170.6,NaN
97,키즈,공룡랜드,광령평화2길 1,9.0,NaN,NaN,11370.0,NaN
101,키즈,액트몬(신화월드점),신화역사로304번길 38,3.5,NaN,NaN,1512.0,NaN
102,키즈,코코몽에코파크,536 제주코코몽에코파크,6.4,NaN,NaN,1539.6,NaN
104,테마관광,건강과성박물관,성 박물관,15.4,NaN,NaN,1423.2,박물관
105,테마관광,공룡랜드,광령평화2길 1,8.8,NaN,NaN,14000.0,NaN
110,테마관광,더마파크,155 더마파크,29.5,NaN,NaN,14400.0,NaN
112,테마관광,메이즈랜드,2134-47 메이즈랜드,208.8,NaN,NaN,696.3,NaN
114,테마관광,브릭캠퍼스,1100로 3047,11.5,NaN,NaN,9556.5,NaN
115,테마관광,브릭캠퍼스,3047 브릭캠퍼스,24.9,NaN,NaN,6207.1,NaN
117,테마관광,상효원,산록남로 2847-37,6.1,NaN,NaN,12802.8,NaN
121,테마관광,쇠소깍산물관광농원,하례로 90,3.2,NaN,NaN,10133.5,NaN
122,테마관광,스누피가든,금백조로 930,757.1,NaN,NaN,6327.5,NaN
123,테마관광,신화테마파크제주,98 신화테마파크,25.5,NaN,NaN,12835.3,NaN
126,테마관광,여미지식물원,중문관광로 93,59.6,NaN,NaN,7912.6,NaN
127,테마관광,오설록 티뮤지엄,15 오설록,29.1,NaN,NaN,9341.7,박물관
132,테마관광,제주돌마을공원,421 제주돌마을공원,4.8,NaN,NaN,21302.3,NaN
134,테마관광,제주무민랜드,병악로 420,17.3,NaN,NaN,8220.7,NaN
144,테마관광,하모씨워킹,최남단해안로 120,3.4,NaN,NaN,9129.4,NaN
148,테마관광,화조원,애원로 804,47.8,NaN,NaN,2500.0,NaN

In [13]:
unique_nm = carbon['TRRSRT_NM'].unique()

In [14]:
len(unique_nm)

119

In [15]:
count = [0] * len(unique_nm)

for i in range(len(unique_nm)):
    for j in range(len(carbon)):
        if unique_nm[i] == carbon['TRRSRT_NM'][j]:
            count[i] += 1
        else:
            pass

In [16]:
idx = []

for i in range(len(count)):
    if count[i] > 1:
        idx.append(i)

In [17]:
rep_nm = []

for i in idx:
    rep_nm.append(unique_nm[i])

In [18]:
rep_nm

['건강과성박물관',
 '그대나의뮤즈',
 '노형수퍼마_',
 '빛의벙커',
 '세계자동차박물관',
 '아프리카박물관',
 '유리박물관',
 '점보빌리지',
 '제주해양동물박물관',
 '초콜릿랜드',
 '캐릭파크',
 '피규어뮤지엄',
 '헬로키티아일랜드',
 '마라도가는여객선',
 '사뿐',
 '산방산탄산온천',
 '삼성혈',
 '성산포유람선',
 '쇠소깍산물관광농원',
 '오설록 티뮤지엄',
 '코코몽에코파크',
 '제주민속촌',
 '상효원',
 '여미지식물원',
 '공룡랜드',
 '뽀로로앤타요 테마파크',
 '더마파크',
 '메이즈랜드',
 '브릭캠퍼스',
 '제주돌마을공원']

In [19]:
carbon['Duplicate_status'] = False

In [20]:
for i in range(len(carbon)):
    if carbon['TRRSRT_NM'][i] in rep_nm:
        carbon['Duplicate_status'][i] = True

/var/folders/_t/yrhf8bh167g1b6qb6gqjrf_c0000gn/T/ipykernel_971/895174581.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  carbon['Duplicate_status'][i] = True

In [21]:
carbon_rep = carbon[carbon['Duplicate_status'] == True]

In [22]:
carbon_rep = carbon_rep.sort_values('TRRSRT_NM')

In [24]:
carbon_rep

,CL_NM,TRRSRT_NM,ADDR,AVERAGE_VISITOR,Gas,Avg_Gas,price_per_person,Duplicate_status
0,공연전시,건강과성박물관,일주서로 1611,10.5,10.268741,0.977975,10535.9,True
104,테마관광,건강과성박물관,성 박물관,15.4,NaN,NaN,1423.2,True
97,키즈,공룡랜드,광령평화2길 1,9.0,NaN,NaN,11370.0,True
105,테마관광,공룡랜드,광령평화2길 1,8.8,NaN,NaN,14000.0,True
20,기타,그대나의뮤즈,제주신화월드 서머셋클럽하우스,23.4,NaN,NaN,14611.9,True
2,공연전시,그대나의뮤즈,신화역사로304번길 89,8.3,93.480535,11.262715,14772.3,True
81,문화관광,노형수퍼마_,노형로 89,23.4,7.498472,0.320448,15278.7,True
4,공연전시,노형수퍼마_,노형로 89,16.8,7.498472,0.446338,14120.5,True
110,테마관광,더마파크,155 더마파크,29.5,NaN,NaN,14400.0,True
109,테마관광,더마파크,월림7길 155,28.2,26.581168,0.942595,16200.0,True
26,기타,마라도가는여객선,424 마라도여객선매표소,17.8,NaN,NaN,16697.0,True
55,레저,마라도가는여객선,송악관광로 424,8.8,0.873520,0.099264,16788.6,True
111,테마관광,메이즈랜드,비자림로 2134-47,113.8,10.926960,0.096019,13977.6,True
112,테마관광,메이즈랜드,2134-47 메이즈랜드,208.8,NaN,NaN,696.3,True
114,테마관광,브릭캠퍼스,1100로 3047,11.5,NaN,NaN,9556.5,True
115,테마관광,브릭캠퍼스,3047 브릭캠퍼스,24.9,NaN,NaN,6207.1,True
5,공연전시,빛의벙커,고성리 2039-22,424.6,NaN,NaN,17564.5,True
32,기타,빛의벙커,고성리 2039-22,754.1,NaN,NaN,17519.9,True
99,키즈,뽀로로앤타요 테마파크,병악로 269,18.6,10.843026,0.582958,10588.3,True
116,테마관광,뽀로로앤타요 테마파크,병악로 269,27.8,10.843026,0.390037,6011.5,True
33,기타,사뿐,오일장동길 36,3.3,1.588218,0.481278,445.0,True
34,기타,사뿐,36 원화하이츠빌라,1.0,NaN,NaN,8640.0,True
35,기타,산방산탄산온천,사계북로41번길 192,9.5,29.417221,3.096550,9398.9,True
59,레저,산방산탄산온천,사계북로41번길 192,9.9,29.417221,2.971436,9048.3,True
82,문화관광,삼성혈,삼성로 22,4.2,1.506269,0.358635,2228.3,True
36,기타,삼성혈,삼성로 22,3.2,1.506269,0.470709,3403.4,True
87,자연,상효원,산록남로 2847-37,7.7,NaN,NaN,9000.0,True
117,테마관광,상효원,산록남로 2847-37,6.1,NaN,NaN,12802.8,True
64,레저,성산포유람선,성산읍 성산리,15.5,NaN,NaN,11986.4,True
37,기타,성산포유람선,성산읍 성산리,6.7,NaN,NaN,12680.9,True
38,기타,세계자동차박물관,세계자동차 제주박물관,12.2,NaN,NaN,11524.0,True
6,공연전시,세계자동차박물관,중산간서로 1610,10.2,0.436368,0.042781,10855.6,True
39,기타,쇠소깍산물관광농원,하례로 90,2.0,NaN,NaN,4000.0,True
121,테마관광,쇠소깍산물관광농원,하례로 90,3.2,NaN,NaN,10133.5,True
125,테마관광,아프리카박물관,이어도로 49,9.5,5.692265,0.599186,14794.4,True
9,공연전시,아프리카박물관,이어도로 49,8.3,5.692265,0.685815,7618.2,True
90,자연,여미지식물원,중문관광로 93,60.4,NaN,NaN,13000.0,True
126,테마관광,여미지식물원,중문관광로 93,59.6,NaN,NaN,7912.6,True
42,기타,오설록 티뮤지엄,신화역사로 15,15.2,NaN,NaN,21661.1,True
127,테마관광,오설록 티뮤지엄,15 오설록,29.1,NaN,NaN,9341.7,True
128,테마관광,유리박물관,중산간서로 1403,3.8,9.411031,2.476587,9456.5,True
10,공연전시,유리박물관,중산간서로 1403,3.3,9.411031,2.851828,7800.0,True
11,공연전시,점보빌리지,평화로319번길 31-11,12.1,7.452377,0.615899,8345.6,True
130,테마관광,점보빌리지,평화로319번길 31-11,12.0,7.452377,0.621031,20969.2,True
131,테마관광,제주돌마을공원,금능남로 421,4.5,0.355283,0.078952,16293.3,True
132,테마관광,제주돌마을공원,421 제주돌마을공원,4.8,NaN,NaN,21302.3,True
83,문화관광,제주민속촌,민속해안로 631-34,24.2,10.681458,0.441383,8279.0,True
135,테마관광,제주민속촌,민속해안로 631-34,12.1,10.681458,0.882765,10162.0,True
12,공연전시,제주해양동물박물관,서성일로 689-21,6.8,2.922076,0.429717,6848.3,True
138,테마관광,제주해양동물박물관,서성일로 689-21,19.3,2.922076,0.151403,7547.5,True
13,공연전시,초콜릿랜드,중문관광로110번길 15,2.5,18.949955,7.579982,750.0,True
139,테마관광,초콜릿랜드,중문관광로110번길 15,4.0,18.949955,4.737489,12344.9,True
14,공연전시,캐릭파크,선교로 266,4.2,0.922703,0.219691,12988.7,True
141,테마관광,캐릭파크,선교로 266,5.0,0.922703,0.184541,5184.2,True
46,기타,코코몽에코파크,536 제주코코몽에코파크,10.8,NaN,NaN,13314.4,True
102,키즈,코코몽에코파크,536 제주코코몽에코파크,6.4,NaN,NaN,1539.6,True
143,테마관광,피규어뮤지엄,한창로 243,30.2,4.069010,0.134735,12092.9,True
16,공연전시,피규어뮤지엄,한창로 243,16.0,4.069010,0.254313,8957.0,True
17,공연전시,헬로키티아일랜드,한창로 340,34.0,15.460906,0.454733,11663.1,True
147,테마관광,헬로키티아일랜드,한창로 340,49.7,15.460906,0.311085,7044.6,True

In [25]:
avg['Duplicate_status'] = False

for i in range(len(avg)):
    if avg['TRRSRT_NM'][i] in rep_nm:
        avg['Duplicate_status'][i] = True

/var/folders/_t/yrhf8bh167g1b6qb6gqjrf_c0000gn/T/ipykernel_971/3952711164.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  avg['Duplicate_status'][i] = True

In [26]:
avg_rep_df = avg[avg['Duplicate_status']==True]

In [27]:
carbon

,CL_NM,TRRSRT_NM,ADDR,AVERAGE_VISITOR,Gas,Avg_Gas,price_per_person,Duplicate_status
0,공연전시,건강과성박물관,일주서로 1611,10.5,10.268741,0.977975,10535.9,True
1,공연전시,고흐의 정원,삼달신풍로 126-5,5.2,0.264908,0.050944,7271.4,False
2,공연전시,그대나의뮤즈,신화역사로304번길 89,8.3,93.480535,11.262715,14772.3,True
3,공연전시,그림포레스트,중문관광로110번길 32,9.0,18.391061,2.043451,10075.4,False
4,공연전시,노형수퍼마_,노형로 89,16.8,7.498472,0.446338,14120.5,True
...,...,...,...,...,...,...,...,...
144,테마관광,하모씨워킹,최남단해안로 120,3.4,NaN,NaN,9129.4,False
145,테마관광,한림공원,한림로 300,75.5,20.802554,0.275531,9255.3,False
146,테마관광,허브동산,돈오름로 170,17.1,8.259299,0.483000,5609.5,False
147,테마관광,헬로키티아일랜드,한창로 340,49.7,15.460906,0.311085,7044.6,True
148,테마관광,화조원,애원로 804,47.8,NaN,NaN,2500.0,False

In [39]:
avg_rep_df['AVERAGE_VISITOR'] = round(avg_rep_df['AVERAGE_VISITOR'], 1)

/var/folders/_t/yrhf8bh167g1b6qb6gqjrf_c0000gn/T/ipykernel_971/903499157.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  avg_rep_df['AVERAGE_VISITOR'] = round(avg_rep_df['AVERAGE_VISITOR'], 1)

In [40]:
avg_rep_df

       TRRSRT_NM  AVERAGE_VISITOR  Duplicate_status
2        건강과성박물관             11.6              True
5           공룡랜드              8.8              True
6         그대나의뮤즈             14.2              True
16          더마파크             28.5              True
22      마라도가는여객선             10.6              True
28         메이즈랜드            161.3              True
34         브릭캠퍼스             14.8              True
37          빛의벙커            499.4              True
38   뽀로로앤타요 테마파크             22.4              True
39            사뿐              3.0              True
42       산방산탄산온천              9.7              True
43           삼성혈              3.6              True
44           상효원              6.6              True
53        성산포유람선             14.6              True
54      세계자동차박물관             10.7              True
60     쇠소깍산물관광농원              3.0              True
68       아프리카박물관              8.6              True
70        여미지식물원             60.0              True
73      오설록 티뮤지엄             17.7              True
77         유리박물관              3.6              True
80         점보빌리지             12.1              True
82       제주돌마을공원              4.6              True
86         제주민속촌             18.5              True
94     제주해양동물박물관             13.9              True
103        초콜릿랜드              2.8              True
105         캐릭파크              4.5              True
107      코코몽에코파크              9.0              True
114       피규어뮤지엄             23.4              True
122     헬로키티아일랜드             41.9              True

In [35]:
for i in range(len(carbon)):
    if carbon['Duplicate_status'][i] == True:
        nm = carbon['TRRSRT_NM'][i]
        avg_visit = avg_rep_df[avg_rep_df['TRRSRT_NM'] == nm]['AVERAGE_VISITOR']
        carbon['AVERAGE_VISITOR'] = float(avg_visit)

2    11.645455
Name: AVERAGE_VISITOR, dtype: float64
6    14.234375
Name: AVERAGE_VISITOR, dtype: float64
Series([], Name: AVERAGE_VISITOR, dtype: float64)
37    499.454545
Name: AVERAGE_VISITOR, dtype: float64
54    10.673469
Name: AVERAGE_VISITOR, dtype: float64
68    8.595745
Name: AVERAGE_VISITOR, dtype: float64
77    3.631579
Name: AVERAGE_VISITOR, dtype: float64
80    12.11
Name: AVERAGE_VISITOR, dtype: float64
94    13.90678
Name: AVERAGE_VISITOR, dtype: float64
103    2.8
Name: AVERAGE_VISITOR, dtype: float64
105    4.481481
Name: AVERAGE_VISITOR, dtype: float64
114    23.36747
Name: AVERAGE_VISITOR, dtype: float64
122    41.929825
Name: AVERAGE_VISITOR, dtype: float64
6    14.234375
Name: AVERAGE_VISITOR, dtype: float64
22    10.54878
Name: AVERAGE_VISITOR, dtype: float64
37    499.454545
Name: AVERAGE_VISITOR, dtype: float64
39    3.0
Name: AVERAGE_VISITOR, dtype: float64
39    3.0
Name: AVERAGE_VISITOR, dtype: float64
42    9.716049
Name: AVERAGE_VISITOR, dtype: float64
43    3.567568
Name: AVERAGE_VISITOR, dtype: float64
53    14.588235
Name: AVERAGE_VISITOR, dtype: float64
54    10.673469
Name: AVERAGE_VISITOR, dtype: float64
60    3.0
Name: AVERAGE_VISITOR, dtype: float64
73    17.684211
Name: AVERAGE_VISITOR, dtype: float64
107    9.0
Name: AVERAGE_VISITOR, dtype: float64
22    10.54878
Name: AVERAGE_VISITOR, dtype: float64
42    9.716049
Name: AVERAGE_VISITOR, dtype: float64
53    14.588235
Name: AVERAGE_VISITOR, dtype: float64
Series([], Name: AVERAGE_VISITOR, dtype: float64)
43    3.567568
Name: AVERAGE_VISITOR, dtype: float64
86    18.480769
Name: AVERAGE_VISITOR, dtype: float64
44    6.62037
Name: AVERAGE_VISITOR, dtype: float64
70    60.0
Name: AVERAGE_VISITOR, dtype: float64
5    8.791667
Name: AVERAGE_VISITOR, dtype: float64
38    22.417808
Name: AVERAGE_VISITOR, dtype: float64
107    9.0
Name: AVERAGE_VISITOR, dtype: float64
2    11.645455
Name: AVERAGE_VISITOR, dtype: float64
5    8.791667
Name: AVERAGE_VISITOR, dtype: float64
16    28.518519
Name: AVERAGE_VISITOR, dtype: float64
16    28.518519
Name: AVERAGE_VISITOR, dtype: float64
28    161.288235
Name: AVERAGE_VISITOR, dtype: float64
28    161.288235
Name: AVERAGE_VISITOR, dtype: float64
34    14.745098
Name: AVERAGE_VISITOR, dtype: float64
34    14.745098
Name: AVERAGE_VISITOR, dtype: float64
38    22.417808
Name: AVERAGE_VISITOR, dtype: float64
44    6.62037
Name: AVERAGE_VISITOR, dtype: float64
60    3.0
Name: AVERAGE_VISITOR, dtype: float64
68    8.595745
Name: AVERAGE_VISITOR, dtype: float64
70    60.0
Name: AVERAGE_VISITOR, dtype: float64
73    17.684211
Name: AVERAGE_VISITOR, dtype: float64
77    3.631579
Name: AVERAGE_VISITOR, dtype: float64
80    12.11
Name: AVERAGE_VISITOR, dtype: float64
82    4.6
Name: AVERAGE_VISITOR, dtype: float64
82    4.6
Name: AVERAGE_VISITOR, dtype: float64
86    18.480769
Name: AVERAGE_VISITOR, dtype: float64
94    13.90678
Name: AVERAGE_VISITOR, dtype: float64
103    2.8
Name: AVERAGE_VISITOR, dtype: float64
105    4.481481
Name: AVERAGE_VISITOR, dtype: float64
114    23.36747
Name: AVERAGE_VISITOR, dtype: float64
122    41.929825
Name: AVERAGE_VISITOR, dtype: float64

In [47]:
price[price['TRRSRT_NM'] == '노형수퍼마켙']

,CL_NM,TRRSRT_NM,ADDR,TOT_ENTRN_NMPR_CO,SETLE_PRICE,PRICE_PER_PERSON
4,공연전시,노형수퍼마켙,제주시 노형로 89,1407,19867560,14120.5
81,문화관광,노형수퍼마켙,제주시 노형로 89,585,8938020,15278.7